spring.application.name=enterprise-ai-backend
spring.data.mongodb.uri=mongodb+srv://naresh556:naresh556@cluster0.yzcwdck.mongodb.net/enterprise_ai_db?retryWrites=true&w=majority&appName=cluster0
server.port=8080

# --- Email Notifications Configuration (Task Allocation) ---
# Replace the username and password with actual Gmail API credentials
# Using dummy values so Spring doesn't crash on startup and uses fallback Exception logs
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dekiru0076@gmail.com
spring.mail.password=xsdwazajngjkzbcd
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.mail.properties.mail.smtp.ssl.trust=smtp.gmail.com
spring.mail.properties.mail.debug=true